# Generated by Django 4.2.14 on 2024-07-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('last_won', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WinningNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(unique=True)),
                ('numbers', models.CharField(max_length=20)),
                ('bonus', models.IntegerField()),
                ('jackpot', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='draw_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='win_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='win_type',
            field=models.CharField(default='No Win', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.34, max_digits=6),
        ),
    ]
