# Generated by Django 5.0.7 on 2024-07-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default='72pKFbheqw', max_length=10, unique=True),
        ),
    ]
