# Generated by Django 5.0.7 on 2024-07-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='bonus_number',
            new_name='bonus',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
