# Generated by Django 4.2.14 on 2024-07-20 01:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_rename_bonus_number_ticket_bonus_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('user', 'numbers', 'bonus')},
        ),
    ]
