# Generated by Django 4.2.14 on 2024-10-04 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ticket_unique_together_account_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackpot',
            name='last_won',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
