# Generated by Django 4.2.14 on 2024-10-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_jackpot_last_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackpot',
            name='last_won',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
