# Generated by Django 4.2.14 on 2024-10-04 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_jackpot_last_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackpot',
            name='last_won',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
