# Generated by Django 4.2.14 on 2024-10-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ticket_draw_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='draw_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_per_draw',
            field=models.DecimalField(decimal_places=2, default=1.34, max_digits=10),
            preserve_default=False,
        ),
    ]
