# Generated by Django 4.2.14 on 2024-10-04 19:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ticket_draw_count_ticket_price_per_draw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price_per_draw',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.34'), max_digits=10),
        ),
    ]
