# Generated by Django 4.2.14 on 2024-10-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ticket_price_per_draw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='draw_count',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='draw_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_per_draw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
