# Generated by Django 4.2.14 on 2024-10-05 03:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_ticket_draw_count_ticket_ticket_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='win_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='win_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
