# Generated by Django 4.2.14 on 2024-10-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ticket_ticket_number_alter_ticket_win_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='next_drawing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
